### PR TITLE
Only consider files with '.tar' and '.tgz' extensions in bundle logic

### PR DESCRIPTION
**Pull request by rhiadj**
As part of a project I'm working on we'd like to use shrinkpack - however we'd like to use a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in order to store the node packages in a separate repository.

This has several advantages - the main two being:
- if we ever choose to change our packaging logic in future we won't have megabytes/gigabytes of tar files in the repo forever which are not used and can't easily be removed
- if developers need to they can still clone (just) the application codebase without the need to download all the packages (very useful when e.g. traveling)

With this in mind we set up the repo as follows:

```
codebase
    |
    +--- .git 
    +--- README.md
    +--- package.json
    +--- node_shrinkwrap  <<  this is a git submodule - points to another repo hence has it's own .git
            |
            +--- .git
            +--- README.md
```

However we can't do this currently as whenever we run `shrinkpack` it removes the `.git` and `README.md` (and any other file) inside `node_shrinkwrap` as part of the deletion logic:
```
$ shrinkpack

> codebase@0.1.0 shrinkpack /Workspace/codebase
> shrinkpack --keep-optional

- .git
- README.md
+ ansi-regex-0.1.0.tar
+ strip-ansi-0.2.2.tar
... etc
```

In order to work around this I've tweaked the bundle logic slightly so that it only considers files ending in `.tar` and `.tgz` during various operations.

Interested to get your thoughts on this?

Notes:
I tried to run the tests (on a vanilla clone) but got cryptic errors so wasn't able to add any additional tests for this new logic - or indeed check if any were failing (sorry about this I did try!).

Thanks

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks @rhiadj, very happy to include this 👍  I'll pick it up when I next time I update shrinkpack.

**Comment by rhiadj** [comment]
Brilliant! Thanks @JamieMason - much appreciated 👍

**Comment by JamieMason** [comment]
Sorry for the wait, this will make it in eventually :+1:

**Comment by JamieMason** [comment]
When finished, the new version that supports npm 5 should account for this: https://github.com/JamieMason/shrinkpack/blob/dev/src/lib/get-unused-tars.js#L6. Anything that isn't a tar or tgz will be ignored.

**Comment by rhiadj** [comment]
Great stuff - thanks for the update @JamieMason 

Don't worry too much re the wait - I've been using a cloned/patched version from my repo for now but will def move back to your mainline release once this is in.

As always - much appreciated and keep up the fantastic work! This tool has saved me countless hours already!

**Comment by JamieMason** [comment]
Great :+1:

**Comment by JamieMason** [comment]
Because #83 is blocked I thought I'd look at releasing this and some other small changes while we wait. 

Unfortunately though [the build](https://travis-ci.org/JamieMason/shrinkpack/builds/280142115) is having a strange issue running `npm install -g npm@4.4.3` in Travis and I'm now on holiday for a week. I will pick this back up when I return, thanks.

**Comment by rhiadj** [comment]
@JamieMason no worries at all - as it happens I've jumped ship to yarn now (which has similar functionality built in) so this isn't as important as it was. Obviously feel free to continue this as is/was. I'm very grateful for all your help - best of luck for the future!

**Pull request closed without merging**
