### PR TITLE
Fixed typo in README file

### PR DESCRIPTION
**Pull request by dtolstyi**

### CODE REVIEW

**Comment by JamieMason** [comment]
Thanks a lot for this @GitAngel, could you resubmit with the commit message following [the naming convention](https://github.com/JamieMason/shrinkpack/commits/master) though please? eg. docs(readme): fix grammar. 👍

**Comment by dtolstyi** [comment]
Sure.
Will do this now.
Sorry for not following naming conventions.

**Comment by dtolstyi** [comment]
@JamieMason, should be ok now.

**Comment by JamieMason** [comment]
Perfect, thanks very much – I'll merge this in next time I work on shrinkpack.

Much appreciated.

**Comment by dtolstyi** [comment]
Great.

Thank you, @Jamie, and good luck.

Kind regards,
Dmytro TOLSTYI

2016-05-17 14:43 GMT+02:00 Jamie Mason notifications@github.com:

**Pull request merged**
